@host=https://localhost:7005

POST {{host}}/api/users
Content-Type: application/json

{
  "firstname": "firstname1",
  "lastname": "lastname1",
  "isSuperAdmin": false,
  "password": "password1",
  "email": "user8@example.com"
}