@host=https://localhost:7005
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiTWF4IiwiZmFtaWx5X25hbWUiOiJNdXN0ZXIiLCJlbWFpbCI6Im1heC5tdXN0ZXJAZXhhbXBsZS5jb20iLCJpZCI6IjEzIiwicm9sZXMiOiIiLCJ1c2VyTWVtYmVyIjoiNiIsImFkbWluTWVtYmVyIjoiIiwiZXhwIjoxNzE4NjQxNzQxLCJpc3MiOiJUcmlwSGVscGVyIiwiYXVkIjoiVHJpcEhlbHBlciJ9.gndnhZVeEWu3jmpiO1ro8bVsXPzQ65SZnEhkdckgdrM

POST {{host}}/api/users
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "firstname": "Max",
  "lastname": "Muster",
  "isSuperAdmin": false,
  "password": "aBc123!@#",
  "email": "max2.muster@example.com"
}