@host=https://localhost:7005
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF0cmljayIsImZhbWlseV9uYW1lIjoiVG9tYSIsImVtYWlsIjoicGF0cmljay50b21hQGdteC5jaCIsImlkIjoiOCIsInJvbGVzIjoiU3VwZXIgQWRtaW4iLCJ1c2VyTWVtYmVyIjoiIiwiYWRtaW5NZW1iZXIiOiI1IiwiZXhwIjoxNzE4NjQwNTgyLCJpc3MiOiJUcmlwSGVscGVyIiwiYXVkIjoiVHJpcEhlbHBlciJ9.G5GjdidoZJHkntis_U2oySbfbxW2eehJOj8L5uUBQko
@userId=8

GET {{host}}/api/users/{{userId}}
Authorization: Bearer {{token}}