@host=https://localhost:7005
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGF0cmljayIsImZhbWlseV9uYW1lIjoiVG9tYSIsImVtYWlsIjoicGF0cmljay50b21hQGdteC5jaCIsImlkIjoiOCIsInJvbGVzIjoiU3VwZXIgQWRtaW4iLCJ1c2VyTWVtYmVyIjoiIiwiYWRtaW5NZW1iZXIiOiI2IiwiZXhwIjoxNzE5NTE1NTYwLCJpc3MiOiJwYXRyaWNrX2lzc3VlciIsImF1ZCI6IlRyaXBIZWxwZXIifQ.Gazt60_o0m6Xf21g1Nv8EHCudP9IZKDBHAD0q3s7wZg

POST {{host}}/api/members
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "max.muster@example.com",
  "tripId": 7,
  "isAdmin": false
}